var audio_crow0 = document.createElement("audio");
audio_crow0.src='audio/crow1.wav'
var audio_crow1 = document.createElement("audio");
audio_crow1.src='audio/crow1.wav'
var audio_music0 = document.createElement("audio");
audio_music0.src='audio/music0.m4a'
audio_music0.loop=true;
var audio_music1 = document.createElement("audio");
audio_music1.src='audio/music1.wav'
audio_music1.loop=true;
var audio_ambient0 = document.createElement("audio");
audio_ambient0.src='audio/ambient0.wav'
audio_ambient0.volume=0.5
audio_ambient0.loop=true;
var audio_ambient1 = document.createElement("audio");
audio_ambient1.src='audio/ambient1.wav'
audio_ambient1.volume=0.5
audio_ambient1.loop=true;
var audio_ambient2 = document.createElement("audio");
audio_ambient2.src='audio/ambient2.wav'
audio_ambient2.volume=0.5
audio_ambient2.loop=true;
var audio_point_cheer = document.createElement("audio");
audio_point_cheer.src='audio/point_cheer.wav'
audio_point_cheer.volume=0.4;
var audio_horn = document.createElement("audio");
audio_horn.src='audio/horn.wav'
var audio_swish = document.createElement("audio");
audio_swish.src='audio/swish.wav'